//import { ItemProducts, ServiceCategory } from '@prisma/client'

export const categories = [
  {
    id: 1,
    name: "Computer & Office",
  },
  {
    id: 2,
    name: "Games & Entertainment",
  },
  {
    id: 3,
    name: "Hardware & Components",
  },
  {
    id: 4,
    name: "Headphones, Speakers & Microphones",
  },
  {
    id: 5,
    name: "Home Appliance",
  },
  {
    id: 6,
    name: "Laptops, Tablets & PCs",
  },
  {
    id: 7,
    name: "Photo / Video",
  },
  {
    id: 8,
    name: "Smartphones, Radio & GPS",
  },
  {
    id: 9,
    name: "Tools & Machines",
  },
  {
    id: 10,
    name: "TV / HiFi / Video",
  },
];

export const products = [
  {
    id: "58629",
    name: "TERMO PEABODY PE-ETA1000S E_TERMO - A.INOX, 1LT, 700W, INC. MATE/BOMBILLA",
    brand: "PEABODY",
    stock: "1985",
    price: "10202.35378",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58629_800.jpg",
    state: "A",
    categoryId: "5",
    priceSpecial: "0",
    category: { id: 5, name: "Home Appliance" },
  },
  {
    id: "43857",
    name: "MOUSE OPTICO GMX KM-1000 BLACK USB (SOLO P/KIT)",
    brand: "GMX",
    stock: "1",
    price: "2.30246",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/43857_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "55986",
    name: "PLACA RISER VER009S PLUS PCI-E 1X A 16X POWER X SATA (INCLUYE CABLE USB 3.0 Y CABLE SATA/6 PINES)",
    brand: "GENERICO",
    stock: "88",
    price: "6.2576",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/55986_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "55988",
    name: "ADAPTADOR ADD2PSU PARA SINCRONIZAR 2 FUENTES",
    brand: "GENERICO",
    stock: "853",
    price: "2.5803",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/55988_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "55992",
    name: "ADAPTADOR DE NGFF A PCI-E",
    brand: "GENERICO",
    stock: "23",
    price: "2.5404",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/55992_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "44006",
    name: "ROUTER CLASSROOM CLOUD - MYTHWARE - 1WAN POE, 2 LAN (PN:CC-001) INCLUYE DISCO 1TB - 30 LICENCIAS",
    brand: "MYTHWARE",
    stock: "0",
    price: "687.8005",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/44007_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "44007",
    name: "ROUTER CLASSROOM CLOUD - MYTHWARE - 1WAN POE, 2 LAN (PN:CC-001) INCLUYE DISCO 1TB - 40 LICENCIAS",
    brand: "MYTHWARE",
    stock: "0",
    price: "813.46509",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/44007_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "44008",
    name: "ROUTER CLASSROOM CLOUD - MYTHWARE - 1WAN POE, 2 LAN (PN:CC-001) INCLUYE DISCO 1TB - 60 LICENCIAS",
    brand: "MYTHWARE",
    stock: "0",
    price: "859.51065",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/44007_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "54940",
    name: "AMPLIFICADOR INALAMBRICO NEXXT KRONOS 1200 AC - 1200MBPS, DUAL BAND, ENCHUFE P/PARED (AEIEL904A1)",
    brand: "NEXXT",
    stock: "28",
    price: "25.446",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/54940_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "12979",
    name: "CPE OUTDOOR TP-LINK TL-CPE510 - 5.8GHZ MIMO 300MBPS. POE, PANEL 13DBI,27DBM",
    brand: "TP-LINK",
    stock: "1",
    price: "47.352",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/12979_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "15679",
    name: "CPE OUTDOOR TP-LINK TL-CPE610 - 5.8GHZ MIMO 300MBPS. POE, PANEL 23DBI HIGH POWER AP",
    brand: "TP-LINK",
    stock: "0",
    price: "72.09",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/15679_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "40002",
    name: "ACCESS POINT TP-LINK RE200 AC750 - 750MBPS DUAL BAND, EXT. DE RANGO ENCHUFE P/PARED",
    brand: "TP-LINK",
    stock: "25",
    price: "42.3472",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/40002_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "22313",
    name: "ACCESS POINT TP-LINK TL-EAP115 - 300MBPS TECHO/PARED",
    brand: "TP-LINK",
    stock: "0",
    price: "34.4375",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/22313_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "15481",
    name: "RED WIRELESS EXTERIOR PARABOLA UBIQUITI 2.4GHZ 1 ETH 630MVV ROCKET M2 C/FUENTE PoE (ROCKET-M2)",
    brand: "UBIQUITI",
    stock: "0",
    price: "119.49952",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/15481_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "15813",
    name: "RED WIRELESS EXTERIOR PARABOLA UBIQUITI 5.8GHZ 1 ETH 25DBI 400MW POWERBEAM C/FUENTE PoE (PBE-M5-400)",
    brand: "UBIQUITI",
    stock: "0",
    price: "159.76256",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/15813_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "52234",
    name: "COOLER AEROCOOL CYLON 3H -ARGB, PWM 4P-  (1200/115X/775/FM1/FM2/AM3+/AM3/AM2+/AM2/AM4)",
    brand: "AEROCOOL",
    stock: "3",
    price: "32.7027",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/52234_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "54813",
    name: "COOLER AEROCOOL VERKHO I (115X/1200/775)",
    brand: "AEROCOOL",
    stock: "66",
    price: "8.1917",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/54813_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "112714",
    name: "CABLE KVM 3 MTRS. VGA/PS2 D-LINK (PN: DKVM-CB3)",
    brand: "D-LINK",
    stock: "0",
    price: "19.49301",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/112714_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "112711",
    name: "CABLE KVM 3 MTRS. VGA/PS2/USB D-LINK P/KVM-440/50 (PN: KVM-402)",
    brand: "D-LINK",
    stock: "0",
    price: "31.97729",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/112711_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "55705",
    name: "HUB USB 3.0 DE 4 PUERTOS CON INTERRUPTOR POR PUERTO (KQ008H)",
    brand: "INTCO",
    stock: "0",
    price: "1899.43",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/55705_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "47047",
    name: "DISCO RIGIDO EXTERNO 4TB SEAGATE USB 3.0 (STEA4000400)",
    brand: "SEAGATE",
    stock: "0",
    price: "101.1352",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/47034_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "47034",
    name: "DISCO RIGIDO BARRACUDA 1TB SEAGATE SATA 6 64MB ( ST1000DM010)",
    brand: "SEAGATE",
    stock: "0",
    price: "44.303",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/47034_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "53003",
    name: "DISCO RIGIDO SKYHAWK 1TB SEAGATE SATA 64MB INTEGRACION (ST1000VX008)",
    brand: "SEAGATE",
    stock: "0",
    price: "51.86",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/53003_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "57663",
    name: "DISCO RIGIDO WD PURPLE 2TB (WD22PURZ)",
    brand: "WESTERN DIGITAL",
    stock: "75",
    price: "63.0779",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/57663_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "57383",
    name: "DISCO SSD WD BLACK SN770 500GB M2 NVME 5150MB (WDS500G3X0E)",
    brand: "WESTERN DIGITAL",
    stock: "255",
    price: "92.6819",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/57383_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "4845",
    name: "DVD-R BULK X 50 UTIL-OF MEDIA (0156) VANTA X UNIDAD",
    brand: "GENERICO",
    stock: "0",
    price: "4.79203",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/4845_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "53413",
    name: "CCTV HIKVISION DVR 8 CH ACUSENSE,1 SATA HASTA 10TB, SOPORTA RECONOCIMIENTO FACIAL (IDS-7208HQHI-M1)",
    brand: "HIKVISION",
    stock: "15",
    price: "197.55",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/53413_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "57506",
    name: "CCTV HIKVISION DVR 8 CH TURBO HD 4.0, 2 CH IP, 1 SATA HASTA 4TB, H.265 PRO+ (DS-7208HGHI-K1)",
    brand: "HIKVISION",
    stock: "21",
    price: "126.165",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/57506_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "15502",
    name: "ZAPATILLA ATOMLUX R2200 2 PUERTOS USB, 3 TOMACORRIENTES 3 SALIDAS Y 2MTRS DE CABLE",
    brand: "ATOMLUX",
    stock: "26",
    price: "2029.059",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/15502_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "48342",
    name: "ESTABILIZADOR DE TENSION FORZA FVR-1202A 220V 1200VA/600W 6-IRAM (FVR-1202A)",
    brand: "FORZA",
    stock: "0",
    price: "20.77",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/48342_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "48346",
    name: "ESTABILIZADOR DE TENSION FORZA FVR-1602A 220V 1600VA/800W 6-IRAM (FVR-1602A)",
    brand: "FORZA",
    stock: "147",
    price: "28.48999",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/48346_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "35532",
    name: "ESTABILIZADOR DE TENSION LYONN 2000VA (1400 WATT) TIPO ZAPATILLA (TCA-2000NV)",
    brand: "LYONN",
    stock: "0",
    price: "26.004",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/35532_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "3900",
    name: "PINZA CRIMPEADORA RJ45/RJ11/R12 NISUTA (NSPIRRJ45)",
    brand: "GENERICO",
    stock: "3",
    price: "1452.62",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/3900_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "56567",
    name: "MINI PINZA UNIVERSAL MEGALITE (ZD7003)",
    brand: "MEGALITE",
    stock: "0",
    price: "566.21426",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/56567_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "56569",
    name: "ALICATE PARA CABLE COAXIAL MEGALITE (ZD2021)",
    brand: "MEGALITE",
    stock: "0",
    price: "789.94634",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/56569_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "47832",
    name: "FICHA RJ45 PLASTICA REFORZADA CON METAL PARA CCTV",
    brand: "NET QUALITY",
    stock: "680",
    price: "0.196",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/56929_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "32028",
    name: "CAMARA FILMADORA DEPORTIVA PCBOX JUNIOR CAM  PCB-C720K AMARILLA - 1080P - FOTOS 5MP  -120° - PANTALL",
    brand: "PCBOX",
    stock: "37",
    price: "23.9049",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/32028_800.jpg",
    state: "A",
    categoryId: "7",
    priceSpecial: "0",
    category: { id: 7, name: "Photo / Video" },
  },
  {
    id: "56929",
    name: "FUENTE ADATA XPG CORE REACTOR 850W 80 PLUS GOLD (COREREACTOR850G-BKCAR)",
    brand: "ADATA",
    stock: "317",
    price: "121.2695",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/56929_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "56931",
    name: "FUENTE ADATA XPG CYBERCORE 1000W 80 PLUS PLATINUM (CYBERCORE1000P-BKCAR)",
    brand: "ADATA",
    stock: "48",
    price: "215.1334",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/56931_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "58179",
    name: "FUENTE AEROCOOL MIRAGE GOLD 750W (ARGB, APFC, FULL RANGE, FULLY MODULAR)",
    brand: "AEROCOOL",
    stock: "241",
    price: "100.4936",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58179_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "58181",
    name: "FUENTE AEROCOOL MIRAGE GOLD 850W (ARGB, APFC, FULL RANGE, FULLY MODULAR)",
    brand: "AEROCOOL",
    stock: "369",
    price: "109.3617",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58181_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "58617",
    name: "FUENTE SWITCHING 24V 2AMP P/VOLANTE LOGITECH PLUG 2.1MM",
    brand: "BELSIC",
    stock: "27",
    price: "12.6",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58617_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "54299",
    name: "FUENTE GIGABYTE GP-P1000GM 1000W 80 PLUS GOLD",
    brand: "GIGABYTE",
    stock: "19",
    price: "169.6852",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/54299_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "33678",
    name: "FUENTE SEASONIC 850 WATT REAL 80PLUS FOCUS GOLD (PN:SSR-850FX)",
    brand: "SEASONIC",
    stock: "189",
    price: "161.7656",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/33678_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "44841",
    name: "FUENTE SEASONIC 1000 WATT REAL FOCUS GX-1000 (PN SSR-1000FX)",
    brand: "SEASONIC",
    stock: "72",
    price: "213.38968",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/44841_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "44843",
    name: "FUENTE SEASONIC 750 WATT REAL FOCUS GM-750 80+GOLD (PN SSR-750FM)",
    brand: "SEASONIC",
    stock: "88",
    price: "127.02997",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/44843_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "46607",
    name: "FUENTE SEASONIC 1300 WATT REAL PRIME GX-1300 (PN SSR-1300GD)",
    brand: "SEASONIC",
    stock: "82",
    price: "304.3083",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/46607_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "4528",
    name: "FUENTE DE ALIMENTACION PARA LEDS 12V 3.5AMP PCBOX CON CHICOTES",
    brand: "MAENI",
    stock: "1",
    price: "19.06612",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/4528_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "4529",
    name: "FUENTE DE ALIMENTACION PARA LEDS 12V 5AMP PCBOX CON CHICOTES",
    brand: "MAENI",
    stock: "3",
    price: "22.67256",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/4529_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "55956",
    name: "PUNTAS ATORNILLADOR KWB PH2 - 1/4 X 25 mm X 25  (49120092)",
    brand: "EINHELL",
    stock: "0",
    price: "1226.42",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/55956_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "58333",
    name: "LINTERNA TACTICA 10WLED 6/2HS BATERIA LITIO Y USB (8020)",
    brand: "ATOMLUX",
    stock: "4",
    price: "3484.5",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58333_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "54913",
    name: "TALADRO DE IMPACTO DAIHATSU TI500K - 500W 3000RPM",
    brand: "DAIHATSU",
    stock: "1",
    price: "9621.408",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/54913_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "52875",
    name: "ATORNILLADOR DAIHATSU HI-A36M - INALAMBRICO 3.6V CON MECHAS",
    brand: "DAIHATSU",
    stock: "0",
    price: "10317.775",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/52875_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "55730",
    name: "LUSTRALIJADORA ORBITAL DAIHATSU LL1200PRO - 180MM - 3600RPM VARIABLE - 1200W",
    brand: "DAIHATSU",
    stock: "0",
    price: "24566.825",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/55730_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "42898",
    name: "TALADRO ATORNILLADOR EINHELL TE-CD 18-40 LI BL SOLO - INALAMBRICO (4513997)",
    brand: "EINHELL",
    stock: "2",
    price: "13868.478",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/42898_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "55954",
    name: "TALADRO ATORNILLADOR EINHELL TE-CD 12/1 X-LI - INALAMBRICO 12 V, (1×2,0 AH) (4513592)",
    brand: "EINHELL",
    stock: "4",
    price: "19888.232",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/55954_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "59556",
    name: "ADAPTADOR DE PUNTAS A 90ª (49118410)",
    brand: "EINHELL",
    stock: "2",
    price: "4343.027",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/59556_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "59572",
    name: "PACK DE 2 BATERIAS POWER X-CHANGE 2 x 2,5 AH (4511518)",
    brand: "EINHELL",
    stock: "6",
    price: "11529.011",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/59572_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "8880",
    name: "GRASA SILICONADA JERINGA 10CC DELTA (GS)",
    brand: "DELTA",
    stock: "44",
    price: "359.437",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/8880_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "16303",
    name: "COMPITT NTBK, KIT DE LIMPIEZA DE NOTEBOOK DELTA 60CC + 4 PAÑOS (NT)",
    brand: "DELTA",
    stock: "0",
    price: "846.9875",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/16303_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "52424",
    name: "COMPITT OR, REMOVEDOR DE PARTICULAS DELTA S/GATILLO 250GR (COR)",
    brand: "DELTA",
    stock: "0",
    price: "1246.311",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/52424_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "1019",
    name: "COMPITT OR, REMOVEDOR DE PARTICULAS DELTA C/ GATILLO 450GR (ORGA)",
    brand: "DELTA",
    stock: "25",
    price: "2902.406",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/1019_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "48616",
    name: "VINCHA DE PROTECCIÓN FACIAL",
    brand: "GENERICO",
    stock: "41",
    price: "218.13221",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/48616_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "52940",
    name: "MEMORIA UDIMM ADATA XPG SPECTRIX D50G RGB DDR4 16GB 3200MHZ GREY BOX (AX4U320016G16A-ST50)",
    brand: "ADATA",
    stock: "4",
    price: "110.0452",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/52940_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "52623",
    name: "MEMORIA UDIMM NEO FORZA DDR4 16GB 2666MHZ - BLISTER (NMUD416E82-2666EA10 / NMUD416E82-2666EA10)",
    brand: "NEO FORZA",
    stock: "0",
    price: "64.4579",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/49575_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "54183",
    name: "MEMORIA UDIMM NEO FORZA 16GB DDR4 4000MHZ BLACK (NMUD416E82-4000FG10)",
    brand: "NEO FORZA",
    stock: "0",
    price: "67.4052",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/54183_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "43715",
    name: "MEMORIA MICROSD WD PURPLE 32GB C10 (WDD032G1P0A)",
    brand: "WESTERN DIGITAL",
    stock: "0",
    price: "7.52",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/43715_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "46402",
    name: "DFROBOT KIT INICIAL PARA MICROBIT (SKU: DFR0497-1)",
    brand: "DFROBOT",
    stock: "74",
    price: "118.26405",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/46402_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "47566",
    name: "DFROBOT VALIJA GRUPAL PARA MICROBIT (SKU: EDU0037)",
    brand: "DFROBOT",
    stock: "25",
    price: "704.33057",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/47566_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "57482",
    name: "MICROFONO NOGANET STREAMER HI-FI UNIDIRECCIONAL USB CON ESTRUTURA DE AGARRE Y FILTRO (MIC-ST700)",
    brand: "NOGANET",
    stock: "2",
    price: "4018.95",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/57482_800.jpg",
    state: "A",
    categoryId: "4",
    priceSpecial: "0",
    category: { id: 4, name: "Headphones, Speakers & Microphones" },
  },
  {
    id: "49703",
    name: 'MONITOR LED 19.5" ACER V206HQL ABI HDMI+VGA 16:9 1600x900 5MS (UM.IV6AA.A09)',
    brand: "ACER",
    stock: "5",
    price: "138.3071",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/49703_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "56941",
    name: "MOUSE ADATA XPG INFAREX M20 OPTICAL 5000 DPI RGB (INFAREX M20)",
    brand: "ADATA",
    stock: "22",
    price: "19.1148",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/56941_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "54288",
    name: "MOUSE HP PAVILION GAMING 300 (4PH30AA#ABL)",
    brand: "HP",
    stock: "0",
    price: "22.7918",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/54288_800.jpg",
    state: "A",
    categoryId: "2",
    priceSpecial: "0",
    category: { id: 2, name: "Games & Entertainment" },
  },
  {
    id: "45925",
    name: "MOUSE KLIPXTREME WIRELESS RESTING PAD BUSINESS BLACK FLEXOR (KMW-750)",
    brand: "KLIPXTREME",
    stock: "45",
    price: "13.8801",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/54288_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "45942",
    name: "MOUSE KLIPXTREME OPTICO KMO-111 USB 1600 DPI SHADOW (KMO-111)",
    brand: "KLIPXTREME",
    stock: "238",
    price: "3.72009",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/45925_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "47410",
    name: "MOUSE KLIPXTREME WIRELESS  ERGONOMICO BLACK ORBIX (KMW-500BK)",
    brand: "KLIPXTREME",
    stock: "31",
    price: "11.95624",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/47410_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "47419",
    name: "MOUSE KLIPXTREME OPTICO USB GALET 1000DPI (KMO-120BK)",
    brand: "KLIPXTREME",
    stock: "93",
    price: "4.10023",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/47419_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "48987",
    name: "MOUSE INALÁMBRICO KLIPXTREME TRACKBALL ERGOBALL (KMW-800)",
    brand: "KLIPXTREME",
    stock: "0",
    price: "26.47706",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/48987_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "49737",
    name: "MOUSE KLIPXTREME WIRELESS KX Mse Wls KMW-356BL 2.4 GHz Blue Nano Dngl",
    brand: "KLIPXTREME",
    stock: "26",
    price: "7.94118",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/48987_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "51663",
    name: "MOUSE KLIPXTREME WIRELESS OPTICO  (KMO-310BK)",
    brand: "KLIPXTREME",
    stock: "52",
    price: "7.30211",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/51663_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "54931",
    name: "MOUSE KLIPXTREME KREST OPTICO ULTRA ERGONOMICO OPTICO USB  (KMO-505)",
    brand: "KLIPXTREME",
    stock: "46",
    price: "11.06448",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/54931_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "54933",
    name: "MOUSE KLIPXTREME KROWN OPTICO ULTRA ERGONOMICO OPTICO USB  (KMO-506)",
    brand: "KLIPXTREME",
    stock: "39",
    price: "10.27416",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/54933_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "57634",
    name: "MOUSE INALÁMBRICO KLIPXTREME BT 5.0 FUTIVO (KMB-001GR)",
    brand: "KLIPXTREME",
    stock: "83",
    price: "8.61036",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/57634_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "45947",
    name: "MOUSE KLIPXTREME WIRELESS KMW-BL 6 BOTONES NANO DONGLE RED VECTOR (KMW-340RD)",
    brand: "KLIPXTREME",
    stock: "56",
    price: "6.93079",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/45947_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "11644",
    name: "MOUSE LOGITECH M90 USB NEGRO PC/MAC (PN:910-004053)",
    brand: "LOGITECH",
    stock: "1863",
    price: "3.262",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/11644_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "41220",
    name: "MOUSE LOGITECH WIRELESS MINI M187 USB REFRESH LIGHT BLUE (PN:910-005363)",
    brand: "LOGITECH",
    stock: "0",
    price: "9.8349",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/41220_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "42717",
    name: "MOUSE LOGITECH M110 SILENT AZUL USB (910-005491)",
    brand: "LOGITECH",
    stock: "144",
    price: "4.7281",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/42717_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "42719",
    name: "MOUSE LOGITECH M110 SILENT GRIS USB (910-005494)",
    brand: "LOGITECH",
    stock: "319",
    price: "4.7525",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/42719_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "58952",
    name: "MOUSE LOGITECH POP with emoji HEARTBREAKER WIRELESS ROSA (910-006551)",
    brand: "LOGITECH",
    stock: "535",
    price: "26.6213",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58952_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "58959",
    name: "MOUSE PAD LOGITECH 200x230mm NEGRO (956-000035)",
    brand: "LOGITECH",
    stock: "328",
    price: "8.1855",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58959_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "58963",
    name: "MOUSE PAD LOGITECH 200x230mm ROSA (956-000037)",
    brand: "LOGITECH",
    stock: "173",
    price: "8.1855",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58963_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "58964",
    name: "MOUSE PAD LOGITECH 200x230mm AZUL (956-000038)",
    brand: "LOGITECH",
    stock: "174",
    price: "8.1855",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58964_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "58966",
    name: "MOUSE PAD LOGITECH 70x30CM LAVANDA (956-000036)",
    brand: "LOGITECH",
    stock: "51",
    price: "16.3222",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58966_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "58328",
    name: "MOUSE PAD LOGITECH 70x30CM (PN:956-000047)",
    brand: "LOGITECH",
    stock: "48",
    price: "16.3343",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58328_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "59011",
    name: "MOUSE PAD LOGITECH 70x30CM (PN:956-000048)",
    brand: "LOGITECH",
    stock: "106",
    price: "16.3222",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/59011_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "59013",
    name: "MOUSE LOGITECH POP with emoji HEARTBREAKER WIRELESS AMARILLO (910-006549)",
    brand: "LOGITECH",
    stock: "12",
    price: "26.6213",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/59013_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "59014",
    name: "MOUSE LOGITECH POP with emoji HEARTBREAKER WIRELESS LILA (910-006550)",
    brand: "LOGITECH",
    stock: "713",
    price: "26.6213",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/59014_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "46052",
    name: "MOUSE XTECH XTM-410 ÓPTICO OPHIDIAN ILUMINADO 6 BOTONES (XTM-410)",
    brand: "XTECH",
    stock: "15",
    price: "7.19523",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/46052_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "46053",
    name: "MOUSE XTECH XTM-510 ÓPTICO BELLIXUS ILUMINADO 6 BOTONES (XTM-510)",
    brand: "XTECH",
    stock: "23",
    price: "9.57799",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/46053_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "46054",
    name: "MOUSE XTECH XTM-610 ÓPTICO LETHAL HAZE ILUMINADO 6 BOTONES ID011XTK11 (XTM-610)",
    brand: "XTECH",
    stock: "88",
    price: "10.2425",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/46054_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "47569",
    name: "MOUSE XTECHÓPTICO MICE ILUMINADO 6 BOTONES  (XTM-710)",
    brand: "XTECH",
    stock: "46",
    price: "9.74565",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/47569_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "47573",
    name: "MOUSE XTECH  3D ÓPTICO (XTM-175)",
    brand: "XTECH",
    stock: "582",
    price: "2.13644",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/47573_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "23362",
    name: "PROTECTOR DE VIDRIO TEMPLADO PCBOX PCB-IPH6",
    brand: "PCBOX",
    stock: "3",
    price: "2.51856",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/23362_800.jpg",
    state: "A",
    categoryId: "8",
    priceSpecial: "0",
    category: { id: 8, name: "Smartphones, Radio & GPS" },
  },
  {
    id: "41427",
    name: "RADIO RELOJ ANALOG VICTROLA BROADWAY BLUETOOTH (VC-150-MAH)",
    brand: "VICTROLA",
    stock: "2",
    price: "69.01381",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/41427_800.jpg",
    state: "A",
    categoryId: "8",
    priceSpecial: "0",
    category: { id: 8, name: "Smartphones, Radio & GPS" },
  },
  {
    id: "43923",
    name: "RADIO RELOJ ANALOG VICTROLA BROADWAY BLUETOOTH (VC-150-WHT)",
    brand: "VICTROLA",
    stock: "23",
    price: "68.76856",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/43923_800.jpg",
    state: "A",
    categoryId: "8",
    priceSpecial: "0",
    category: { id: 8, name: "Smartphones, Radio & GPS" },
  },
  {
    id: "42428",
    name: "SOPORTE DE SCANNERS EPSON PARA HOJAS (B12B819051)",
    brand: "EPSON",
    stock: "0",
    price: "35.4182",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/42428_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "46405",
    name: "SENSOR SIGUE LÍNEAS DFROBOT GRAVITY PARA ARDUINO (SKU: SEN0017)",
    brand: "DFROBOT",
    stock: "10",
    price: "7.30393",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/46405_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "46406",
    name: "SENSOR ULTRASÓNICO DFROBOT PARA ARDUINO (SKU: SEN0001)",
    brand: "DFROBOT",
    stock: "10",
    price: "20.80582",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/46406_800.jpg",
    state: "A",
    categoryId: "3",
    priceSpecial: "0",
    category: { id: 3, name: "Hardware & Components" },
  },
  {
    id: "19592",
    name: "ACCESORIO CAMARA GOPRO 3D HERO SYSTEM (GOPAHD3D-001) - P/ HERO/HERO2",
    brand: "GOPRO",
    stock: "0",
    price: "1190.38166",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/19592_800.jpg",
    state: "A",
    categoryId: "7",
    priceSpecial: "0",
    category: { id: 7, name: "Photo / Video" },
  },
  {
    id: "24954",
    name: "SELFIE STICK PCBOX MDQ PCB-W65MDQ SELFIE STICK RIGIDO WATERPROOF LARGO 65CM",
    brand: "PCBOX",
    stock: "93",
    price: "21.00375",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/24954_800.jpg",
    state: "A",
    categoryId: "7",
    priceSpecial: "0",
    category: { id: 7, name: "Photo / Video" },
  },
  {
    id: "56097",
    name: 'BASE XTECH PARA NOTEBBOKS 14" C/ Ventilador KYLA - LED 2 PTOS USB  (XTA-150)',
    brand: "XTECH",
    stock: "94",
    price: "10.45589",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/56097_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "45966",
    name: "SOPORTE PROYECTOR KLIPXTREME KPM-410B BLACK AC124KLX01 (KPM-410B)",
    brand: "KLIPXTREME",
    stock: "7",
    price: "17.71845",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/45966_800.jpg",
    state: "A",
    categoryId: "10",
    priceSpecial: "0",
    category: { id: 10, name: "TV / HiFi / Video" },
  },
  {
    id: "47506",
    name: "SOPORTE PROYECTOR KLIPXTREME WHITE (KPM-400W)",
    brand: "KLIPXTREME",
    stock: "10",
    price: "12.46912",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/47506_800.jpg",
    state: "A",
    categoryId: "10",
    priceSpecial: "0",
    category: { id: 10, name: "TV / HiFi / Video" },
  },
  {
    id: "57883",
    name: "KLIPX NOTEBOOK STAND BLACK 4 USB PORT-FAN AN120KLX52 (KNS-110B)",
    brand: "KLIPXTREME",
    stock: "69",
    price: "25.28092",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/57883_800.jpg",
    state: "A",
    categoryId: "10",
    priceSpecial: "0",
    category: { id: 10, name: "TV / HiFi / Video" },
  },
  {
    id: "47578",
    name: 'SOPORTE TV LED XTECH 32" / 70" 30 KG FIJO (XTA-375)',
    brand: "XTECH",
    stock: "3",
    price: "13.21652",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/47578_800.jpg",
    state: "A",
    categoryId: "10",
    priceSpecial: "0",
    category: { id: 10, name: "TV / HiFi / Video" },
  },
  {
    id: "12746",
    name: "TESTER DIGITAL Y DE RED UTP TODO EN UNO NISUTA (PN:NSTEDI2)",
    brand: "NISUTA",
    stock: "2",
    price: "5535.66",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/12746_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "22265",
    name: 'TABLET LENOVO TB- M10-X505F 10", 16 GB, 2GB GBL-AR (ZA4G0077AR)',
    brand: "LENOVO",
    stock: "1159",
    price: "151.0972",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/22265_800.jpg",
    state: "A",
    categoryId: "6",
    priceSpecial: "0",
    category: { id: 6, name: "Laptops, Tablets & PCs" },
  },
  {
    id: "54721",
    name: 'TABLET LENOVO YT11 SMART J706F 4GB 128GB 11" (ZA8W0010AR)',
    brand: "LENOVO",
    stock: "140",
    price: "354.625",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/54721_800.jpg",
    state: "A",
    categoryId: "6",
    priceSpecial: "0",
    category: { id: 6, name: "Laptops, Tablets & PCs" },
  },
  {
    id: "56551",
    name: 'TABLET LENOVO YT13 SMART K606F 13" 8GB 128GB  (ZA8E0024AR)',
    brand: "LENOVO",
    stock: "3",
    price: "719.672",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/56551_800.jpg",
    state: "A",
    categoryId: "6",
    priceSpecial: "0",
    category: { id: 6, name: "Laptops, Tablets & PCs" },
  },
  {
    id: "55547",
    name: 'TABLET PCBOX PCB-T104+ FLASH PLUS - PANTALLA 10.1"IPS 1280*800 -32GB+2GB- CAMARA 0.3MP+2MP-BT 4.1-AN',
    brand: "PCBOX",
    stock: "291",
    price: "119.7789",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/55547_800.jpg",
    state: "A",
    categoryId: "6",
    priceSpecial: "0",
    category: { id: 6, name: "Laptops, Tablets & PCs" },
  },
  {
    id: "56935",
    name: "TECLADO MECANICO ADATA XPG MAGE RED SWITCH ESP RGB (MAGE105RD-BKCES)",
    brand: "ADATA",
    stock: "37",
    price: "56.5422",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/56935_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "54286",
    name: "TECLADO HP KEYBOARD 100 (2UN30AA#ABM)",
    brand: "HP",
    stock: "1",
    price: "13.2276",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/54286_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "57429",
    name: "TECLADO GAMER HYPERX ALLOY MKW100 RED HKBM1-R-US/G (4P5E1AA#ABA)",
    brand: "HyperX",
    stock: "57",
    price: "55.8092",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/57429_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "45936",
    name: "TECLADO KLIPXTREME STYLUS ID211KLX10 (KKS-050S)",
    brand: "KLIPXTREME",
    stock: "87",
    price: "5.42242",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/45936_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "45941",
    name: "COMBO TECLADO Y MOUSE INALAMBRICOS KLIPXTREME KCK-265S INSPIRE (KCK-265S)",
    brand: "KLIPXTREME",
    stock: "74",
    price: "15.25068",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/45941_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "47418",
    name: "TECLADO KLIPXTREME NUMERICO ABACUS (KNP-100)",
    brand: "KLIPXTREME",
    stock: "75",
    price: "7.56488",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/47418_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "37203",
    name: "TECLADO LOGITECH G413 MECANICAL GAMING KEYBOARD CARBON (920-008300)",
    brand: "LOGITECH",
    stock: "9",
    price: "83.7",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/37203_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "45682",
    name: "TECLADO LOGITECH G213 GAMING PRODIGY ESP (920-008086)",
    brand: "LOGITECH",
    stock: "49",
    price: "45.771",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/45682_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "47346",
    name: "TECLADO LOGITECH GAMING G815 RGB MECHANICAL (920-008984)",
    brand: "LOGITECH",
    stock: "0",
    price: "131.1104",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/47346_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "58938",
    name: "TECLADO LOGITECH G413 TKL SE MECANICAL GAMING NEGRO (920-010442)",
    brand: "LOGITECH",
    stock: "25",
    price: "66.0218",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58938_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "58962",
    name: "TECLADO LOGITECH MX KEYS MINI WIRELESS GRIS (920-010477)",
    brand: "LOGITECH",
    stock: "227",
    price: "70.762",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58962_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "58330",
    name: "TECLADO LOGITECH MX KEYS MINI WIRELESS ROSA (920-010478)",
    brand: "LOGITECH",
    stock: "55",
    price: "70.5542",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58330_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "58937",
    name: "TECLADO LOGITECH G413 MECANICAL GAMING NEGRO (920-010433)",
    brand: "LOGITECH",
    stock: "13",
    price: "71.6294",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/58937_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "46068",
    name: "TECLADO XTECH XTK-130 MULTIMEDIA USB ESPAÑOL ID222XTK01  (XTK-130)",
    brand: "XTECH",
    stock: "335",
    price: "5.24156",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/46068_800.jpg",
    state: "A",
    categoryId: "1",
    priceSpecial: "0",
    category: { id: 1, name: "Computer & Office" },
  },
  {
    id: "45851",
    name: "UPS FORZA INTERACTIVA SERIE NT 500VA/250W TORRE, 4 TOMAS IRAM, 220V, LUZ LED (NT-502A)",
    brand: "FORZA",
    stock: "29",
    price: "56.16",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/45851_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "46212",
    name: "UPS FORZA INTERACTIVA SERIE SL 1000VA/600W TORRE, 6 TOMAS IRAM, 220V, CABLE, SOFT, LCD (SL-1012UL-A)",
    brand: "FORZA",
    stock: "7",
    price: "157.67",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/46212_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "55283",
    name: "FORZA SL-1502UL-A SMART UPS 1500VA/900W 220V 4-IRAM 1100J RJ45  (SL-1502UL-A)",
    brand: "FORZA",
    stock: "59",
    price: "238.42",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/46212_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "55287",
    name: "FORZA SL-2002UL-A SMART UPS 2000VA/1200W 220V 4-IRAM 1100J RJ45  (SL-2002UL-A)",
    brand: "FORZA",
    stock: "55",
    price: "257.93975",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/55287_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "52755",
    name: "UPS FORZA ONLINE ATLAS 1000VA PARA MONTAJE BASTIDOR(FDC-1002R-I) ",
    brand: "FORZA",
    stock: "1",
    price: "470.9862",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/52755_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "7520",
    name: "UPS LYONN DESIRE 500 CON CABLE, SOFT Y DISPLAY TOUCH (DESIRE-500)",
    brand: "LYONN",
    stock: "20",
    price: "54.36",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/52755_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
  {
    id: "56640",
    name: "UPS LYONN ULT-1000RMW-II ON LINE TOWER",
    brand: "LYONN",
    stock: "1",
    price: "423.99989",
    img: "https://www.gruponucleo.com.ar/Temp/App_WebSite/App_PictureFiles/Items/56640_800.jpg",
    state: "A",
    categoryId: "9",
    priceSpecial: "0",
    category: { id: 9, name: "Tools & Machines" },
  },
];



export const customers = [
  {
    email: 'john@customer.com',
    firstName: 'John',
    lastName: 'Customer',
  },
  {
    email: 'jane@customer.com',
    firstName: 'Jane',
    lastName: 'Customer',
  },
  {
    email: 'josh@customer.com',
    firstName: 'Josh',
    lastName: 'Customer',
  },
];