export const SET_ERROR = 'SET_ERROR';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_TOTALARTICULOS = 'GET_TOTALARTICULOS';
export const GET_DETAIL_PRODUCT = 'GET_DETAIL_PRODUCT';
export const GET_ARTICULOS = "GET_ARTICULOS";
export const GET_LOGIN = "GET_LOGIN";